#docker compose up -d
version: '3.3'
services:
  dbserver:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distribuida
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "c:/db-distribuida:/var/lib/postgresql/data"
    ports:
      - "54321:5432"
    expose:
      - 5432
