rootProject.name = "prog-distribuida"
//include("ejemplo01_cdi")
//include("ejemplo_rest")
//include("ejemplo_jpa")
//include("ejemplo_quarkus")
include("app_books")
include("app_authors")
include("app_books_spring")
include("app_authors_spring")
include("sprintboot_authors")
include("sprintboot_books")
