openapi: 3.1.0
info:
  title: Documento Estatico de OpenApi para Authors
  description: Documentacion para Recursos de Authors
  version: "1.0"

servers:
  - url: http://localhost:8080/q/openapi
    description: Visualizacion de la Documentacion en Modo Desarrollador

paths:
